# Grouped Relative Policy Optimization (GRPO) for Code Generation
# >>> python -m apps.coding-grpo.main --config apps/coding-grpo/qwen3_1_7b.yaml

# Global configuration
group_size: 4  # Reduced for longer sequences to avoid OOM
batch_size: 2   # Reduced significantly due to 4096 token sequences
max_req_tokens: 16384  # Increased for coding prompts with examples
max_res_tokens: 16384  # Increased for longer code generation with thinking
model: "Qwen/Qwen3-1.7B"
off_by_n: 1 # Off by one by default

# Main loop configuration
rollout_threads: 1   # Recommended to set equal to policy.num_replicas


# Observability configuration
metric_logging:
  wandb:
    project: "coding-grpo-training"
    group: "coding_grpo_exp_${oc.env:USER}"
    reduce_across_ranks: True
  console:
    reduce_across_ranks: True

# Dataset configuration
dataset:
  path: "TIGER-Lab/AceCode-87K"
  revision: "main"
  data_split: "train"
  streaming: true
  model: ${model}

# Policy configuration
policy:
  engine_config:
    model: ${model}
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    enforce_eager: false
    gpu_memory_utilization: 0.85
    max_model_len: 32768
    enable_chunked_prefill: true
    max_num_batched_tokens: 32768
    max_num_seqs: 12
  sampling_config:
    n: ${group_size}
    max_tokens: ${max_res_tokens}
    temperature: 0.6
    top_p: 0.95

# Trainer configuration
trainer:
  model:
    name: qwen3
    flavor: 1.7B
    hf_assets_path: hf://${model}
  optimizer:
    name: AdamW
    lr: 5e-7
    eps: 1e-8
  lr_scheduler:
    warmup_steps: 1
  training:
    local_batch_size: ${batch_size}
    seq_len: 32768
    max_norm: 0.5
    steps: 2500
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 1
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
    disable_loss_parallel: true
  checkpoint:
    enable: true
    initial_load_path: hf://${model}
    initial_load_in_hf: true
    last_save_in_hf: true
    interval: 250
    async_mode: "disabled"
  activation_checkpoint:
    mode: selective
    selective_ac_option: op

# Replay buffer configuration
replay_buffer:
  batch_size: ${batch_size}
  max_policy_age: ${off_by_n}
  dp_size: ${trainer.parallelism.data_parallel_shard_degree} # Must equal trainer DP degree

# Reference model configuration
ref_model:
  model:
    name: qwen3
    flavor: 1.7B
    hf_assets_path: hf://${model}
  training:
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 1
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
  checkpoint:
    enable: true
    initial_load_path: hf://${model}
    initial_load_in_hf: true

# All resource allocations
services:
  policy:
    procs: ${policy.engine_config.tensor_parallel_size}
    num_replicas: 1
    with_gpus: true
  ref_model:
    procs: 1
    num_replicas: 1
    with_gpus: true
  reward_actor:
    procs: 1
    num_replicas: 1
    with_gpus: false

actors:
  dataset:
    procs: 1
    with_gpus: false
  trainer:
    procs: 1
    with_gpus: true
  replay_buffer:
    procs: 1
    with_gpus: false
  compute_advantages:
    procs: 1
    with_gpus: false
