# -*- coding: utf-8 -*-
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""julia_grpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAcFEKwD0n7HgLVBApQrQn2dK9YoUvu6

# Setting Up unsloth and dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os, importlib.util
# !pip install --upgrade -qqq uv
# if importlib.util.find_spec("torch") is None or "COLAB_" in "".join(os.environ.keys()):
#     try: import numpy; get_numpy = f"numpy=={numpy.__version__}"
#     except: get_numpy = "numpy"
#     !uv pip install -qqq \
#         "torch>=2.8.0" "triton>=3.4.0" {get_numpy} torchvision bitsandbytes "transformers==4.56.2" trackio \
#         "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
#         "unsloth[base] @ git+https://github.com/unslothai/unsloth" \
#         git+https://github.com/triton-lang/triton.git@05b2c186c1b6c9a08375389d5efe9cb4c401c075#subdirectory=python/triton_kernels
# elif importlib.util.find_spec("unsloth") is None:
#     !uv pip install -qqq unsloth trackio
# !uv pip install --upgrade --no-deps transformers==4.56.2 tokenizers trl==0.22.2 unsloth unsloth_zoo

"""# Install the environment and custom openEnv"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -qqq fastapi uvicorn requests
# !git clone https://github.com/yogesh1801/OpenEnv.git > /dev/null 2>&1
# %cd OpenEnv
# !git checkout yogesh-julia-env

import os, subprocess, sys
from pathlib import Path

sys.path.insert(0, "./src")
working_directory = str(Path.cwd().parent.absolute() / "OpenEnv")

"""# Setting up a Model using unsloth which we will train"""

import torch
from unsloth import FastLanguageModel

max_seq_length = 2000
lora_rank = 10
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Llama-3.2-3B-Instruct",
    fast_inference=True,
    load_in_4bit=False,
    max_seq_length=max_seq_length,
    gpu_memory_utilization=0.85,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha=lora_rank,  # *2 speeds up training
    use_gradient_checkpointing="unsloth",  # Reduces memory usage
    random_state=3407,
)

"""# Connecting to julia Env exposed by OpenEnv"""

from envs.julia_env import JuliaEnv
from envs.julia_env.models import JuliaAction, JuliaObservation

"""1. It is not recommended to directly open a subprocess in python instead expose OpenEnv using a docker container because u know that is the whole point of OpenEnv

### First, build the OpenEnv base image (one-time setup):

```bash
# From OpenEnv root directory
docker build -t openenv-base:latest -f src/core/containers/images/Dockerfile .
```

### Build Julia Environment Image

```bash
# From OpenEnv root directory
docker build -t julia-env:latest -f src/envs/julia_env/server/Dockerfile .
```

### Run the Server

```bash
# Run in background
docker run -d -p 8000:8000 --name julia-env-server julia-env:latest

# OR run in foreground (to see logs)
docker run -p 8000:8000 --name julia-env-server julia-env:latest
```


Note this has to be done in system terminal, since this notebook is hosted inside the docker running these commands in terminal exposed by this notebook is illogical as you cannot run docker inside a docker
"""

port = "8000"
localhost = f"http://localhost:{port}"
import time

# openenv_process = subprocess.Popen(
#     [sys.executable, "-m", "uvicorn", "envs.julia_env.server.app:app", "--host", "0.0.0.0", "--port", port],
#     env = {**os.environ,
#          "PYTHONPATH": f"{working_directory}/src",
#          },
#     stdout = subprocess.PIPE,
#     stderr = subprocess.PIPE,
#     text = True,
#     cwd = working_directory,
# )


# used docker images instead

import requests

print(requests.get(f"{localhost}/health", timeout=2).content)
openenv_process = JuliaEnv(base_url=localhost)

result = openenv_process.reset()
current_state = result.observation
current_state

action = JuliaAction(
    core_code="""
module MyProject

export add

function add(a::Number, b::Number)
    return a + b
end

end""",
    test_code="""
using Test
using .MyProject

@testset "Add function Tests" begin
    @test MyProject.add(1, 2) == 3
    @test MyProject.add(1, 2) == 3
    @test Project.add(1, 2) == 3
end
""",
)

result = openenv_process.step(action)
result

"""# Training starts here"""

julia_code_gen_prompt = """
You are a precise and pragmatic Julia programmer.

Write a **single Julia function** that correctly solves the problem described below.

Rules:
- The code must be syntactically correct and runnable as is.
- Do not use arrow functions, ternary operators, or modern syntax that may cause issues.
- Use only the Julia standard library.
- Do **not** wrap the code in a module or add a `main` function.
- Do **not** include any test code in your response.
- Do **not** hardcode specific test cases or outputs — the function must work for general inputs.
- The **function name must exactly match** the one used in the provided tests.
- Respond with **only the Julia function** and nothing else (no explanations, no comments, no extra text)
- The function name must exactly match the one used in the provided tests.
- Return only the Julia function.
- character literal should not contain multiple characters.
- take care of object types and mind that spaces matter in julia so cannot add random spaces

Passing tests and clean, compilable code are rewarded. Hardcoding or failing tests is penalized.

Test Reference (for context only, do not include in the output):
{julia_test}

Code:
""".strip()

import re


def remove_ticks(text):
    text = re.sub(r"^```julia\s*\n?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\n?```\s*$", "", text)

    return text


from trl import GRPOConfig, GRPOTrainer

training_args = GRPOConfig(
    temperature=1.0,
    learning_rate=5e-5,
    weight_decay=0.01,
    warmup_ratio=0.1,
    lr_scheduler_type="linear",
    optim="adamw_8bit",
    logging_steps=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    num_generations=2,
    max_prompt_length=2048,
    max_completion_length=1024,
    num_train_epochs=1,
    max_steps=500,
    save_steps=250,
    report_to="trackio",
    output_dir="outputs",
    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

import pandas as pd
from datasets import Dataset

df = pd.read_parquet("../julia_trainset.parquet")

df = df[["julia_prompt", "julia_test", "first_test_case"]]
dataset = Dataset.from_pandas(df)

dataset = dataset.map(
    lambda x: {
        "prompt": [
            {
                "role": "system",
                "content": julia_code_gen_prompt.format(
                    julia_test=x["first_test_case"]
                ),
            },
            {"role": "user", "content": x["julia_prompt"]},
        ],
    }
)
print(dataset[0])


def julia_env_reward(completions, **kwargs):
    rewards = []
    test_codes_list = kwargs.get("julia_test", [])

    for i, completion in enumerate(completions):
        response = completion[0]["content"]
        core_code = remove_ticks(response)
        test_code = test_codes_list[i]

        try:
            result = openenv_process.reset()
            action = JuliaAction(core_code=core_code, test_code=test_code)
            result = openenv_process.step(action)

            reward = result.reward if result.reward is not None else 0.0

        except Exception as e:
            print(f"Error for completion {i}:", e)
            reward = 0.0

        rewards.append(reward)

    return rewards


trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    remove_unused_columns=False,
    reward_funcs=[julia_env_reward],
    args=training_args,
    train_dataset=dataset,
    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)

trainer.train()

"""# Post training and inferencing"""

model.save_lora("grpo_saved_lora_julia")

from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora_julia/adapter_model.safetensors", framework="pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert n_zeros.item() != tensor.numel()

import pandas as pd
from datasets import Dataset

df = pd.read_parquet("/home/kaiwu/work/amd/amd-submission/julia_trainset.parquet")

df = df[["julia_prompt", "julia_test", "task_id", "first_test_case"]]
dataset = Dataset.from_pandas(df)

MAX_LEN = 2000

dataset = dataset.map(
    lambda x: {
        "prompt": [
            {
                "role": "system",
                "content": julia_code_gen_prompt.format(
                    julia_test=x["first_test_case"]
                )[:MAX_LEN],
            },
            {"role": "user", "content": x["julia_prompt"][:MAX_LEN]},
        ],
    }
)

dataset[0]

import pandas as pd
from tqdm import tqdm
from vllm import SamplingParams

sampling_params = SamplingParams(
    temperature=0.8,
    top_p=0.95,
    max_tokens=1024,
)

results = []

for i in tqdm(range(len(dataset)), desc="Generating Julia Code"):
    task_id = dataset[i]["task_id"]
    julia_test = dataset[i]["julia_test"]
    message = dataset[i]["prompt"]

    text = tokenizer.apply_chat_template(
        message,
        add_generation_prompt=True,
        tokenize=False,
    )

    response = model.fast_generate(
        text,
        sampling_params=sampling_params,
        lora_request=model.load_lora("grpo_saved_lora_julia"),
    )

    julia_code = response[0].outputs[0].text
    julia_code = remove_ticks(julia_code)

    results.append(
        {"task_id": task_id, "julia_code": julia_code, "julia_test": julia_test}
    )

# Save results to parquet
result_df = pd.DataFrame(results)
result_df.to_parquet("julia_code_output_smaller_model.parquet", index=False)

print(
    "✅ Julia code generation completed and saved to julia_code_output_smaller_model.parquet"
)
