# >>> python -m apps.sft_v2.main --config apps/sft_v2/qwen3_8b.yaml


# TODO: required by torchtitan
# https://github.com/pytorch/torchtitan/blob/2f1c814da071cc8ad165d00be6f9c1a66f8e1cce/torchtitan/distributed/utils.py#L265
comm:
  trace_buf_size: 0

model_name: "Qwen/Qwen3-8B"

model:
  name: qwen3
  flavor: 8B
  hf_assets_path: hf://${model_name}

processes:
  procs: 8
  with_gpus: true

optimizer:
  name: AdamW
  lr: 1e-5
  eps: 1e-8

lr_scheduler:
  warmup_steps: 200

training:
  local_batch_size: 1
  seq_len: 2048
  max_norm: 1.0
  steps: 1000
  compile: false
  dataset: "c4"

parallelism:
  data_parallel_replicate_degree: 1
  data_parallel_shard_degree: -1
  tensor_parallel_degree: 1
  pipeline_parallel_degree: 1
  context_parallel_degree: 1
  expert_parallel_degree: 1
  disable_loss_parallel: false

checkpoint:
  enable: true
  initial_load_path: hf://${model_name}
  initial_load_in_hf: true
  last_save_in_hf: true
  interval: 500
  async_mode: "disabled"

activation_checkpoint:
  mode: selective
  selective_ac_option: op

# profiling:
#   enable_profiling: false

# metrics:
#   log_freq: 10
#   enable_tensorboard: true
#   save_tb_folder: "tb"
